server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: Test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

